include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - require_trailing_commas
    - avoid_print # ❌ Don't use print() in production! Use AppLogger.i() instead
    - prefer_single_quotes # Enable for code consistency
    - lines_longer_than_80_chars # Enforce 80 character line limit
    
      # Quote preferences
    - unnecessary_late
    - avoid_final_parameters
    - prefer_final_fields
    - prefer_final_locals
    - library_names
    - sort_pub_dependencies
    - directives_ordering
    - constant_identifier_names
    - non_constant_identifier_names
    - file_names
    - camel_case_extensions
    - prefer_mixin

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    invalid_annotation_target: ignore
    # avoid_print: error # Show print() usage as ERROR


