name: anchored_sheets
description: "A Flutter package to create anchored sheets that can be dragged
  and snapped to different positions on the screen."
version: 1.2.2
homepage: https://github.com/FauziFuzzy/anchored_sheets
repository: https://github.com/FauziFuzzy/anchored_sheets

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
