name: Audit

on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main

jobs:
  analysis:
    name: audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      - run: flutter pub get
          
      - name: Flutter Version
        run: flutter --version

      - name: Run Flutter Analyze
        run: flutter analyze

      - name: Run custom lint
        run: dart run custom_lint

      - name: Flutter analyze
        if: '!cancelled()'
        run: flutter analyze

      - name: Check Code Format
        if: '!cancelled()'
        run: dart format . --set-exit-if-changed